##### openrouteservice settings file #####
# This file contains parameters for openrouteservice.
# For a full list of possible parameters see https://giscience.github.io/openrouteservice/run-instance/configuration/
##### General server settings #####
info:
  app:
    name: ORS API
    version: 1.0.0
    description: ORS API
  author: Tran Khanh Chau
server:
  port: 8082
  error:
    whitelabel:
      enabled: false
  # Keep the context-path at / else the war file run with tomcat will have the context-path of /ors/v2 as well.
  servlet:
    context-path: /ors
  tomcat:
    keep-alive-timeout: 30000

spring:
  application:
    name: ors-api
  profiles:
    active: default
  mvc:
    servlet:
      path: /

##### Settings related to springdoc #####
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    tryItOutEnabled: true
    filter: false
    syntaxHighlight:
      activated: true
    showExtensions: true
  api-docs:
    path: /v2/api-docs
    version: OPENAPI_3_0
  packages-to-scan: org.heigit.ors
  pathsToMatch: /v2/**

##### Logging settings #####
logging:
  file:
    name: ./logs/ors-api.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight{%-7p} %style{%50t}{Cyan} %style{[ %-40.40c{1.} ]}{Bright Cyan}   %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %p [%-40.40c{1.}] - %m%n"
  level:
    root: INFO
    org.heigit: INFO

##### Spring Cloud Eureka settings #####
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${REGISTRATION_URL:http://153.92.5.63:8880/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    non-secure-port-enabled: true
    secure-port-enabled: false
    instance-id: ${INSTANCE_ID:ors-api.io.tkcopart}
    health-check-url-path: ${HEALTH_CHECK_PATH:/actuator/health}
    status-page-url-path: ${STATUS_PATH:/actuator/info}